name: Project Test (CI)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12  # 이름 변경 (선택사항)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # 3.8에서 3.12로 수정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # 테스트 코드가 있다면 여기서 실행 (예: pytest)
